version: "3.9"

services:
  web-system-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-system-core
    ports:
      - "${APP_PORT:-7000}:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: ./db/local.db
    volumes:
      - ./db:/app/db
    restart: unless-stopped
